/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import edu.austral.dissis.checkers.CheckersAdapter
import edu.austral.dissis.chess.gui.*
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage


fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
//    private val gameEngine = SimpleGameEngine()

    val adapter = Adapter()
//    private val gameEngine = adapter.init()
    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GameTitle = "Chess"
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle
        val root = createGameViewFrom(adapter,imageResolver)
        primaryStage.scene = Scene(root)
        primaryStage.show()
    }
}